---
title: "Individual_24nt_siRNA_loci_em_en_ov"
author: "Chenxin Li"
date: "March 22, 2019"
output:
  html_notebook:
    number_sections: yes
    toc: yes
    toc_float: yes
  html_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(emmeans)
library(tidyr)
library(dplyr)
library(readr)
library(readxl)
library(vegan)
library(edgeR)
library(RColorBrewer)
library(stringr)
library(svglite)
```
#g3
##load data
```{r}
wt1_em_egg <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/wt1_em_S45_L005_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_egg-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

wt1_em_sd <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/wt1_em_S45_L005_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_seedling-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

wt1_em_sp <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/wt1_em_S45_L005_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_sperm-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

wt1_em_inter <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/wt1_em_S45_L005_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_sperm-seedling-egg_24siRNAs_intersection.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

```

```{r}
wt2_em_egg <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/wt2_em_combined.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_egg-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

wt2_em_sd <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/wt2_em_combined.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_seedling-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

wt2_em_sp <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/wt2_em_combined.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_sperm-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

wt2_em_inter <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/wt2_em_combined.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_sperm-seedling-egg_24siRNAs_intersection.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)
```

```{r}
wt3_em_egg <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/wt3_em_S47_L005_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_egg-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

wt3_em_sd <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/wt3_em_S47_L005_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_seedling-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

wt3_em_sp <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/wt3_em_S47_L005_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_sperm-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

wt3_em_inter <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/wt3_em_S47_L005_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_sperm-seedling-egg_24siRNAs_intersection.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)
```

```{r}
wt1_en_egg <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/wt1_en_S191_L006_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_egg-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

wt1_en_sd <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/wt1_en_S191_L006_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_seedling-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

wt1_en_sp <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/wt1_en_S191_L006_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_sperm-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

wt1_en_inter <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/WT1_EN~3.MET", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)
```

```{r}
wt2_en_egg <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/wt2_en_S54_L005_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_egg-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

wt2_en_sd <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/wt2_en_S54_L005_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_seedling-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

wt2_en_sp <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/wt2_en_S54_L005_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_sperm-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

wt2_en_inter <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/wt2_en_S54_L005_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_sperm-seedling-egg_24siRNAs_intersection.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)
```

```{r}
wt3_en_egg <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/wt3_en_S55_L005_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_egg-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

wt3_en_sd <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/wt3_en_S55_L005_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_seedling-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

wt3_en_sp <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/wt3_en_S55_L005_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_sperm-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

wt3_en_inter <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/wt3_en_S55_L005_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_sperm-seedling-egg_24siRNAs_intersection.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)
```

```{r}
drm_1_em_egg <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/52_38em_S51_L005_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_egg-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

drm_1_em_sd <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/52_38em_S51_L005_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_seedling-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

drm_1_em_sp <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/52_38em_S51_L005_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_sperm-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

drm_1_em_inter <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/52D79A~1.MET", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)
```

```{r}
drm_2_em_egg <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/52_39em_S52_L005_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_egg-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

drm_2_em_sd <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/52_39em_S52_L005_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_seedling-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

drm_2_em_sp <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/52_39em_S52_L005_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_sperm-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

drm_2_em_inter <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/52_39E~3.MET", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)
```

```{r}
drm_3_em_egg <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/52_40em_S53_L005_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_egg-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

drm_3_em_sd <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/52_40em_S53_L005_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_seedling-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

drm_3_em_sp <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/52_40em_S53_L005_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_sperm-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

drm_3_em_inter <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/52DDF0~1.MET", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)
```

```{r}
drm_1_en_egg <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/52_38en_S194_L006_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_egg-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

drm_1_en_sd <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/52_38en_S194_L006_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_seedling-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

drm_1_en_sp <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/52_38en_S194_L006_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_sperm-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

drm_1_en_inter <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/52_38E~4.MET", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)
```

```{r}
drm_2_en_egg <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/52_39en_S195_L006_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_egg-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

drm_2_en_sd <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/52_39en_S195_L006_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_seedling-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

drm_2_en_sp <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/52_39en_S195_L006_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_sperm-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

drm_2_en_inter <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/529548~1.MET", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)
```

```{r}
drm_3_en_egg <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/52_40en_S196_L006_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_egg-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

drm_3_en_sd <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/52_40en_S196_L006_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_seedling-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

drm_3_en_sp <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/52_40en_S196_L006_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_sperm-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

drm_3_en_inter <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/52_40E~1.MET", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)
```

```{r}
ov1_egg <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/ov1_S49_L003_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_egg-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

ov1_sd <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/ov1_S49_L003_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_seedling-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

ov1_sp <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/ov1_S49_L003_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_sperm-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

ov1_inter <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/ov1_S49_L003_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_sperm-seedling-egg_24siRNAs_intersection.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)
```

```{r}
ov2_egg <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/ov2_S50_L003_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_egg-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

ov2_sd <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/ov2_S50_L003_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_seedling-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

ov2_sp <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/ov2_S50_L003_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_sperm-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

ov2_inter <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/ov2_S50_L003_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_sperm-seedling-egg_24siRNAs_intersection.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)
```

```{r}
ov3_egg <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/ov3_S51_L003_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_egg-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

ov3_sd <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/ov3_S51_L003_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_seedling-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

ov3_sp <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/ov3_S51_L003_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_sperm-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

ov3_inter <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/ov3_S51_L003_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_sperm-seedling-egg_24siRNAs_intersection.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)
```

```{r}
ov4_egg <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/ov4_S4_L001_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_egg-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

ov4_sd <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/ov4_S4_L001_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_seedling-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

ov4_sp <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/ov4_S4_L001_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_sperm-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

ov4_inter <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/ov4_S4_L001_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_sperm-seedling-egg_24siRNAs_intersection.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)
```

```{r}
ov5_egg <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/ov5_S5_L001_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_egg-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

ov5_sd <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/ov5_S5_L001_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_seedling-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

ov5_sp <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/ov5_S5_L001_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_sperm-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

ov5_inter <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/ov5_S5_L001_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_sperm-seedling-egg_24siRNAs_intersection.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)
```

```{r}
ov6_egg <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/ov6_S6_L001_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_egg-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

ov6_sd <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/ov6_S6_L001_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_seedling-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

ov6_sp <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/ov6_S6_L001_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_sperm-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

ov6_inter <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/ov6_S6_L001_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.sorted.bam_sperm-seedling-egg_24siRNAs_intersection.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)
```

##tidy data
```{r}
clean <- function(df){
  df %>% 
    select(X1, X4, X13, X14, X15, X21, X22) %>% 
    filter(X21 > 0.5) %>% 
    filter(X22 >= 2) %>% 
    select(-X21, -X22)
}
```

```{r}
wt1_em_egg1 <- wt1_em_egg %>% 
  clean() %>% 
  mutate(sample_ID = "wt_em1") %>% 
  mutate(bin = "egg-specific") 

colnames(wt1_em_egg1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


wt1_em_sd1 <- wt1_em_sd %>% 
  clean() %>% 
  mutate(sample_ID = "wt_em1") %>% 
  mutate(bin = "seedling-specific")  

colnames(wt1_em_sd1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


wt1_em_sp1 <- wt1_em_sp %>% 
  clean() %>%
  mutate(sample_ID = "wt_em1") %>% 
  mutate(bin = "sperm-specific")  

colnames(wt1_em_sp1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


wt1_em_inter1 <- wt1_em_inter %>% 
  clean() %>% 
  mutate(sample_ID = "wt_em1") %>% 
  mutate(bin = "intersect.")  

colnames(wt1_em_inter1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")
```

```{r}
wt2_em_egg1 <- wt2_em_egg %>% 
  clean() %>% 
  mutate(sample_ID = "wt_em2") %>% 
  mutate(bin = "egg-specific") 

colnames(wt2_em_egg1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


wt2_em_sd1 <- wt2_em_sd %>% 
  clean() %>% 
  mutate(sample_ID = "wt_em2") %>% 
  mutate(bin = "seedling-specific")  

colnames(wt2_em_sd1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


wt2_em_sp1 <- wt2_em_sp %>% 
  clean() %>%
  mutate(sample_ID = "wt_em2") %>% 
  mutate(bin = "sperm-specific")  

colnames(wt2_em_sp1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


wt2_em_inter1 <- wt2_em_inter %>% 
  clean() %>% 
  mutate(sample_ID = "wt_em2") %>% 
  mutate(bin = "intersect.")  

colnames(wt2_em_inter1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")
```

```{r}
wt3_em_egg1 <- wt3_em_egg %>% 
  clean() %>% 
  mutate(sample_ID = "wt_em3") %>% 
  mutate(bin = "egg-specific") 

colnames(wt3_em_egg1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


wt3_em_sd1 <- wt3_em_sd %>% 
  clean() %>% 
  mutate(sample_ID = "wt_em3") %>% 
  mutate(bin = "seedling-specific")  

colnames(wt3_em_sd1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


wt3_em_sp1 <- wt3_em_sp %>% 
  clean() %>%
  mutate(sample_ID = "wt_em3") %>% 
  mutate(bin = "sperm-specific")  

colnames(wt3_em_sp1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


wt3_em_inter1 <- wt3_em_inter %>% 
  clean() %>% 
  mutate(sample_ID = "wt_em3") %>% 
  mutate(bin = "intersect.")  

colnames(wt3_em_inter1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")
```

```{r}
wt1_en_egg1 <- wt1_en_egg %>% 
  clean() %>% 
  mutate(sample_ID = "wt_en1") %>% 
  mutate(bin = "egg-specific") 

colnames(wt1_en_egg1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


wt1_en_sd1 <- wt1_en_sd %>% 
  clean() %>% 
  mutate(sample_ID = "wt_en1") %>% 
  mutate(bin = "seedling-specific")  

colnames(wt1_en_sd1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


wt1_en_sp1 <- wt1_en_sp %>% 
  clean() %>%
  mutate(sample_ID = "wt_en1") %>% 
  mutate(bin = "sperm-specific")  

colnames(wt1_en_sp1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


wt1_en_inter1 <- wt1_en_inter %>% 
  clean() %>% 
  mutate(sample_ID = "wt_en1") %>% 
  mutate(bin = "intersect.")  

colnames(wt1_en_inter1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")
```

```{r}
wt2_en_egg1 <- wt2_en_egg %>% 
  clean() %>% 
  mutate(sample_ID = "wt_en2") %>% 
  mutate(bin = "egg-specific") 

colnames(wt2_en_egg1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


wt2_en_sd1 <- wt2_en_sd %>% 
  clean() %>% 
  mutate(sample_ID = "wt_en2") %>% 
  mutate(bin = "seedling-specific")  

colnames(wt2_en_sd1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


wt2_en_sp1 <- wt2_en_sp %>% 
  clean() %>%
  mutate(sample_ID = "wt_en2") %>% 
  mutate(bin = "sperm-specific")  

colnames(wt2_en_sp1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


wt2_en_inter1 <- wt2_en_inter %>% 
  clean() %>% 
  mutate(sample_ID = "wt_en2") %>% 
  mutate(bin = "intersect.")  

colnames(wt2_en_inter1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")
```

```{r}
wt3_en_egg1 <- wt3_en_egg %>% 
  clean() %>% 
  mutate(sample_ID = "wt_en3") %>% 
  mutate(bin = "egg-specific") 

colnames(wt3_en_egg1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


wt3_en_sd1 <- wt3_en_sd %>% 
  clean() %>% 
  mutate(sample_ID = "wt_en3") %>% 
  mutate(bin = "seedling-specific")  

colnames(wt3_en_sd1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


wt3_en_sp1 <- wt3_en_sp %>% 
  clean() %>%
  mutate(sample_ID = "wt_en3") %>% 
  mutate(bin = "sperm-specific")  

colnames(wt3_en_sp1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


wt3_en_inter1 <- wt3_en_inter %>% 
  clean() %>% 
  mutate(sample_ID = "wt_en3") %>% 
  mutate(bin = "intersect.")  

colnames(wt3_en_inter1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")
```



```{r}
drm_1_em_egg1 <- drm_1_em_egg %>% 
  clean() %>% 
  mutate(sample_ID = "drm_em1") %>% 
  mutate(bin = "egg-specific") 

colnames(drm_1_em_egg1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


drm_1_em_sd1 <- drm_1_em_sd %>% 
  clean() %>% 
  mutate(sample_ID = "drm_em1") %>% 
  mutate(bin = "seedling-specific")  

colnames(drm_1_em_sd1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


drm_1_em_sp1 <- drm_1_em_sp %>% 
  clean() %>%
  mutate(sample_ID = "drm_em1") %>% 
  mutate(bin = "sperm-specific")  

colnames(drm_1_em_sp1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


drm_1_em_inter1 <- drm_1_em_inter %>% 
  clean() %>% 
  mutate(sample_ID = "drm_em1") %>% 
  mutate(bin = "intersect.")  

colnames(drm_1_em_inter1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")
```

```{r}
drm_2_em_egg1 <- drm_2_em_egg %>% 
  clean() %>% 
  mutate(sample_ID = "drm_em2") %>% 
  mutate(bin = "egg-specific") 

colnames(drm_2_em_egg1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


drm_2_em_sd1 <- drm_2_em_sd %>% 
  clean() %>% 
  mutate(sample_ID = "drm_em2") %>% 
  mutate(bin = "seedling-specific")  

colnames(drm_2_em_sd1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


drm_2_em_sp1 <- drm_2_em_sp %>% 
  clean() %>%
  mutate(sample_ID = "drm_em2") %>% 
  mutate(bin = "sperm-specific")  

colnames(drm_2_em_sp1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


drm_2_em_inter1 <- drm_2_em_inter %>% 
  clean() %>% 
  mutate(sample_ID = "drm_em2") %>% 
  mutate(bin = "intersect.")  

colnames(drm_2_em_inter1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")
```

```{r}
drm_3_em_egg1 <- drm_3_em_egg %>% 
  clean() %>% 
  mutate(sample_ID = "drm_em3") %>% 
  mutate(bin = "egg-specific") 

colnames(drm_3_em_egg1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


drm_3_em_sd1 <- drm_3_em_sd %>% 
  clean() %>% 
  mutate(sample_ID = "drm_em3") %>% 
  mutate(bin = "seedling-specific")  

colnames(drm_3_em_sd1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


drm_3_em_sp1 <- drm_3_em_sp %>% 
  clean() %>%
  mutate(sample_ID = "drm_em3") %>% 
  mutate(bin = "sperm-specific")  

colnames(drm_3_em_sp1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


drm_3_em_inter1 <- drm_3_em_inter %>% 
  clean() %>% 
  mutate(sample_ID = "drm_em3") %>% 
  mutate(bin = "intersect.")  

colnames(drm_3_em_inter1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")
```

```{r}
drm_1_en_egg1 <- drm_1_en_egg %>% 
  clean() %>% 
  mutate(sample_ID = "drm_en1") %>% 
  mutate(bin = "egg-specific") 

colnames(drm_1_en_egg1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


drm_1_en_sd1 <- drm_1_en_sd %>% 
  clean() %>% 
  mutate(sample_ID = "drm_en1") %>% 
  mutate(bin = "seedling-specific")  

colnames(drm_1_en_sd1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


drm_1_en_sp1 <- drm_1_en_sp %>% 
  clean() %>%
  mutate(sample_ID = "drm_en1") %>% 
  mutate(bin = "sperm-specific")  

colnames(drm_1_en_sp1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


drm_1_en_inter1 <- drm_1_en_inter %>% 
  clean() %>% 
  mutate(sample_ID = "drm_en1") %>% 
  mutate(bin = "intersect.")  

colnames(drm_1_en_inter1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")
```

```{r}
drm_2_en_egg1 <- drm_2_en_egg %>% 
  clean() %>% 
  mutate(sample_ID = "drm_en2") %>% 
  mutate(bin = "egg-specific") 

colnames(drm_2_en_egg1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


drm_2_en_sd1 <- drm_2_en_sd %>% 
  clean() %>% 
  mutate(sample_ID = "drm_en2") %>% 
  mutate(bin = "seedling-specific")  

colnames(drm_2_en_sd1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


drm_2_en_sp1 <- drm_2_en_sp %>% 
  clean() %>%
  mutate(sample_ID = "drm_en2") %>% 
  mutate(bin = "sperm-specific")  

colnames(drm_2_en_sp1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


drm_2_en_inter1 <- drm_2_en_inter %>% 
  clean() %>% 
  mutate(sample_ID = "drm_en2") %>% 
  mutate(bin = "intersect.")  

colnames(drm_2_en_inter1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")
```

```{r}
drm_3_en_egg1 <- drm_3_en_egg %>% 
  clean() %>% 
  mutate(sample_ID = "drm_en3") %>% 
  mutate(bin = "egg-specific") 

colnames(drm_3_en_egg1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


drm_3_en_sd1 <- drm_3_en_sd %>% 
  clean() %>% 
  mutate(sample_ID = "drm_en3") %>% 
  mutate(bin = "seedling-specific")  

colnames(drm_3_en_sd1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


drm_3_en_sp1 <- drm_3_en_sp %>% 
  clean() %>%
  mutate(sample_ID = "drm_en3") %>% 
  mutate(bin = "sperm-specific")  

colnames(drm_3_en_sp1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


drm_3_en_inter1 <- drm_3_en_inter %>% 
  clean() %>% 
  mutate(sample_ID = "drm_en3") %>% 
  mutate(bin = "intersect.")  

colnames(drm_3_en_inter1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")
```

```{r}
ov1_egg1 <- ov1_egg %>% 
  clean() %>% 
  mutate(sample_ID = "ov1") %>% 
  mutate(bin = "egg-specific") 

colnames(ov1_egg1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


ov1_sd1 <- ov1_sd %>% 
  clean() %>% 
  mutate(sample_ID = "ov1") %>% 
  mutate(bin = "seedling-specific") 

colnames(ov1_sd1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


ov1_sp1 <- ov1_sp %>% 
  clean() %>% 
  mutate(sample_ID = "ov1") %>% 
  mutate(bin = "sperm-specific") 

colnames(ov1_sp1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


ov1_inter1 <- ov1_inter %>% 
  clean() %>% 
  mutate(sample_ID = "ov1") %>% 
  mutate(bin = "intersect.") 

colnames(ov1_inter1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")
```

```{r}
ov2_egg1 <- ov2_egg %>% 
  clean() %>% 
  mutate(sample_ID = "ov2") %>% 
  mutate(bin = "egg-specific") 

colnames(ov2_egg1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


ov2_sd1 <- ov2_sd %>% 
  clean() %>% 
  mutate(sample_ID = "ov2") %>% 
  mutate(bin = "seedling-specific") 

colnames(ov2_sd1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


ov2_sp1 <- ov2_sp %>% 
  clean() %>% 
  mutate(sample_ID = "ov2") %>% 
  mutate(bin = "sperm-specific") 

colnames(ov2_sp1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


ov2_inter1 <- ov2_inter %>% 
  clean() %>% 
  mutate(sample_ID = "ov2") %>% 
  mutate(bin = "intersect.") 

colnames(ov2_inter1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")
```

```{r}
ov3_egg1 <- ov3_egg %>% 
  clean() %>% 
  mutate(sample_ID = "ov3") %>% 
  mutate(bin = "egg-specific") 

colnames(ov3_egg1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


ov3_sd1 <- ov3_sd %>% 
  clean() %>% 
  mutate(sample_ID = "ov3") %>% 
  mutate(bin = "seedling-specific") 

colnames(ov3_sd1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


ov3_sp1 <- ov3_sp %>% 
  clean() %>% 
  mutate(sample_ID = "ov3") %>% 
  mutate(bin = "sperm-specific") 

colnames(ov3_sp1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


ov3_inter1 <- ov3_inter %>% 
  clean() %>% 
  mutate(sample_ID = "ov3") %>% 
  mutate(bin = "intersect.") 

colnames(ov3_inter1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")
```

```{r}
ov4_egg1 <- ov4_egg %>% 
  clean() %>% 
  mutate(sample_ID = "ov4") %>% 
  mutate(bin = "egg-specific") 

colnames(ov4_egg1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


ov4_sd1 <- ov4_sd %>% 
  clean() %>% 
  mutate(sample_ID = "ov4") %>% 
  mutate(bin = "seedling-specific") 

colnames(ov4_sd1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


ov4_sp1 <- ov4_sp %>% 
  clean() %>% 
  mutate(sample_ID = "ov4") %>% 
  mutate(bin = "sperm-specific") 

colnames(ov4_sp1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


ov4_inter1 <- ov4_inter %>% 
  clean() %>% 
  mutate(sample_ID = "ov4") %>% 
  mutate(bin = "intersect.") 

colnames(ov4_inter1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")
```

```{r}
ov5_egg1 <- ov5_egg %>% 
  clean() %>% 
  mutate(sample_ID = "ov5") %>% 
  mutate(bin = "egg-specific") 

colnames(ov5_egg1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


ov5_sd1 <- ov5_sd %>% 
  clean() %>% 
  mutate(sample_ID = "ov5") %>% 
  mutate(bin = "seedling-specific") 

colnames(ov5_sd1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


ov5_sp1 <- ov5_sp %>% 
  clean() %>% 
  mutate(sample_ID = "ov5") %>% 
  mutate(bin = "sperm-specific") 

colnames(ov5_sp1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


ov5_inter1 <- ov5_inter %>% 
  clean() %>% 
  mutate(sample_ID = "ov5") %>% 
  mutate(bin = "intersect.") 

colnames(ov5_inter1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")
```

```{r}
ov6_egg1 <- ov6_egg %>% 
  clean() %>% 
  mutate(sample_ID = "ov6") %>% 
  mutate(bin = "egg-specific") 

colnames(ov6_egg1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


ov6_sd1 <- ov6_sd %>% 
  clean() %>% 
  mutate(sample_ID = "ov6") %>% 
  mutate(bin = "seedling-specific") 

colnames(ov6_sd1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


ov6_sp1 <- ov6_sp %>% 
  clean() %>% 
  mutate(sample_ID = "ov6") %>% 
  mutate(bin = "sperm-specific") 

colnames(ov6_sp1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")


ov6_inter1 <- ov6_inter %>% 
  clean() %>% 
  mutate(sample_ID = "ov6") %>% 
  mutate(bin = "intersect.") 

colnames(ov6_inter1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")
```


```{r}
g3 <- rbind(wt1_em_egg1, wt1_em_sd1, wt1_em_sp1, wt1_em_inter1,
            wt2_em_egg1, wt2_em_sd1, wt2_em_sp1, wt2_em_inter1,
            wt3_em_egg1, wt3_em_sd1, wt3_em_sp1, wt3_em_inter1,
            wt1_en_egg1, wt1_en_sd1, wt1_en_sp1, wt1_en_inter1,
            wt2_en_egg1, wt2_en_sd1, wt2_en_sp1, wt2_en_inter1,
            wt3_en_egg1, wt3_en_sd1, wt3_en_sp1, wt3_en_inter1,
            drm_1_em_egg1, drm_1_em_sd1, drm_1_em_sp1, drm_1_em_inter1,
            drm_2_em_egg1, drm_2_em_sd1, drm_2_em_sp1, drm_2_em_inter1,
            drm_3_em_egg1, drm_3_em_sd1, drm_3_em_sp1, drm_3_em_inter1,
            drm_1_en_egg1, drm_1_en_sd1, drm_1_en_sp1, drm_1_en_inter1,
            drm_2_en_egg1, drm_2_en_sd1, drm_2_en_sp1, drm_2_en_inter1,
            drm_3_en_egg1, drm_3_en_sd1, drm_3_en_sp1, drm_3_en_inter1,
            ov1_egg1, ov1_sd1, ov1_sp1, ov1_inter1,
            ov2_egg1, ov2_sd1, ov2_sp1, ov2_inter1,
            ov3_egg1, ov3_sd1, ov3_sp1, ov3_inter1,
            ov4_egg1, ov4_sd1, ov4_sp1, ov4_inter1,
            ov5_egg1, ov5_sd1, ov5_sp1, ov5_inter1,
            ov6_egg1, ov6_sd1, ov6_sp1, ov6_inter1
            ) %>% 
  mutate(bins = factor(bin, levels = c(
    "egg-specific",
    "seedling-specific",
    "sperm-specific",
    "intersect."
  ))) %>% 
  mutate(sample_type = case_when(
    str_detect(sample_ID, "em") ~ "embryo",
    str_detect(sample_ID, "en") ~ "endosperm",
    str_detect(sample_ID, "ov") ~ "ovary"
  )) %>% 
   mutate(sample_type = factor(sample_type, levels = c("embryo", "endosperm", "ovary"))) %>% 
  mutate(geno = case_when(
    str_detect(sample_ID, "wt") ~ "WT",
    str_detect(sample_ID, "ov") ~ "WT",
    str_detect(sample_ID, "drm") ~ "drm2"
  )) %>% 
  mutate(geno = factor(geno, levels = c("drm2", "WT"))) %>% 
  gather("context", "methylation", 3:5) %>% 
  filter(is.na(methylation) == F) %>% 
  group_by(context, sample_type, geno, start, bins) %>% 
  summarise(methylation = mean(methylation)) %>% 
  ungroup()

```



```{r}
g3 %>% 
  ggplot(aes(x = bins, y = methylation)) +
  facet_grid(context ~ sample_type + geno, scales = "free", space = "free", switch = "both") +
  #geom_bar(stat = "summary", aes(fill = bins), position = position_dodge(), alpha = 0.8, fun.y = mean) +
  stat_summary(geom = "crossbar", fun.data = "median_hilow", width = 0.8, aes(fill = bins), alpha = 0.8) +
  scale_fill_manual(values = c("tomato1", "seagreen", "dodgerblue", "grey60")) +
  labs(x = "methylome",
       fill = NULL,
       y = NULL) +
  theme_minimal()+
  theme(legend.position = "none", strip.placement = "outside") + 
  theme(text = element_text(size= 18, face="bold", colour = "black")) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_text(colour = "black")) 

ggsave(filename = "rice_24nt_bin_meth_em_en_ov_crossbar.svg", height = 5, width = 6.5)
```











Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
