---
title: "Individual 24nt siRNA loci methylation"
author: "Chenxin Li"
date: "March 22, 2019"
output:
  html_notebook:
    number_sections: yes
    toc: yes
    toc_float: yes
  html_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(ggplot2)
library(emmeans)
library(tidyr)
library(dplyr)
library(readr)
library(readxl)
library(vegan)
library(edgeR)
library(RColorBrewer)
library(stringr)
library(svglite)
```

#group1
##load data
```{r}
egg_in_egg <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/egg100.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.nondir6.sorted.bam_egg-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)


egg_in_sd <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/egg100.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.nondir6.sorted.bam_seedling-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

egg_in_sp <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/egg100.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.nondir6.sorted.bam_sperm-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

egg_in_inter <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/egg100.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.nondir6.sorted.bam_sperm-seedling-egg_24siRNAs_intersection.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)
```

```{r}
sperm_in_egg <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/sperm1.split.nondir6.sorted.merged.bam_egg-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)


sperm_in_sd <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/sperm1.split.nondir6.sorted.merged.bam_seedling-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

sperm_in_sp <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/sperm1.split.nondir6.sorted.merged.bam_sperm-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

sperm_in_inter <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/sperm1.split.nondir6.sorted.merged.bam_sperm-seedling-egg_24siRNAs_intersection.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)
```

```{r}
veg1_in_egg <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/veg1_S12_L003_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.nondir6.sorted.bam_egg-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)


veg1_in_sd <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/veg1_S12_L003_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.nondir6.sorted.bam_seedling-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

veg1_in_sp <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/veg1_S12_L003_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.nondir6.sorted.bam_sperm-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

veg1_in_inter <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299~1/SMRNAP~1/METHYL~1/24NT_S~1/24NT_L~1/VEG1_S~2.MET", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)
```

```{r}
veg2_in_egg <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/veg2_S2_L001_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.nondir6.sorted.bam_egg-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)


veg2_in_sd <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/veg2_S2_L001_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.nondir6.sorted.bam_seedling-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

veg2_in_sp <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/veg2_S2_L001_R1_001.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.nondir6.sorted.bam_sperm-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

veg2_in_inter <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/VEG2_S~4.MET", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)
```

```{r}
veg22_in_egg <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/vegetative2.split.nondir6.sorted.merged.bam_egg-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)


veg22_in_sd <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/vegetative2.split.nondir6.sorted.merged.bam_seedling-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

veg22_in_sp <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/vegetative2.split.nondir6.sorted.merged.bam_sperm-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

veg22_in_inter <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/vegetative2.split.nondir6.sorted.merged.bam_sperm-seedling-egg_24siRNAs_intersection.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)
```

```{r}
EC_in_egg <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/SRR5014616-21_EC.split.nondir6.sorted.merged.bam_egg-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)


EC_in_sd <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/SRR5014616-21_EC.split.nondir6.sorted.merged.bam_seedling-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

EC_in_sp <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/SRR5014616-21_EC.split.nondir6.sorted.merged.bam_sperm-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

EC_in_inter <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/SRR5014616-21_EC.split.nondir6.sorted.merged.bam_sperm-seedling-egg_24siRNAs_intersection.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)
```

```{r}
CC_in_egg <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/SRR5014622-28_CC.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.nondir6.sorted.bam_egg-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)


CC_in_sd <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/SRR5014622-28_CC.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.nondir6.sorted.bam_seedling-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

CC_in_sp <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/SRR5014622-28_CC.fastq.gz.trimmed.fastq.gz.filtered.fastq.gz.nondir6.sorted.bam_sperm-specific_24siRNAs.meth", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)

CC_in_inter <- read_delim("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/methylation/24nt_siRNA_loci_methylation Feb20/24nt_loci_meth_individual/SR9FA7~1.MET", 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 1)
```

##tidy data
```{r}
clean <- function(df){
  df %>% 
    select(X1, X4, X13, X14, X15, X21, X22) %>% 
    filter(X21 > 0.5) %>% 
    filter(X22 >= 2) %>% 
    select(-X21, -X22)
  
  #colnames(df) = c("chr", "start", "mCG", "mCHG", "mCHH")
}
```

```{r}
egg_in_egg1 <- clean(egg_in_egg) %>% 
  mutate(sample_ID = "egg100") %>% 
  mutate(bin = "egg-specific")

colnames(egg_in_egg1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")

egg_in_egg2 <- egg_in_egg1 %>% 
  gather("context", "methylation", 3:5)
```

```{r}
egg_in_sd1 <- clean(egg_in_sd) %>% 
  mutate(sample_ID = "egg100") %>% 
  mutate(bin = "seedling-specific")

colnames(egg_in_sd1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")

egg_in_sd2 <- egg_in_sd1 %>% 
  gather("context", "methylation", 3:5)
```

```{r}
egg_in_sp1 <- clean(egg_in_sp) %>% 
  mutate(sample_ID = "egg100") %>% 
  mutate(bin = "sperm-specific")

colnames(egg_in_sp1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")

egg_in_sp2 <- egg_in_sp1 %>% 
  gather("context", "methylation", 3:5)
```

```{r}
egg_in_inter1 <- clean(egg_in_inter) %>% 
  mutate(sample_ID = "egg100") %>% 
  mutate(bin = "intersect.")

colnames(egg_in_inter1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")

egg_in_inter2 <- egg_in_inter1 %>% 
  gather("context", "methylation", 3:5)
```

```{r}
sperm_in_egg1 <- clean(sperm_in_egg) %>% 
  mutate(sample_ID = "sperm1") %>% 
  mutate(bin = "egg-specific")

colnames(sperm_in_egg1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")

sperm_in_egg2 <- sperm_in_egg1 %>% 
  gather("context", "methylation", 3:5)
```

```{r}
sperm_in_sd1 <- clean(sperm_in_sd) %>% 
  mutate(sample_ID = "sperm1") %>% 
  mutate(bin = "seedling-specific")

colnames(sperm_in_sd1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")

sperm_in_sd2 <- sperm_in_sd1 %>% 
  gather("context", "methylation", 3:5)
```

```{r}
sperm_in_sp1 <- clean(sperm_in_sp) %>% 
  mutate(sample_ID = "sperm1") %>% 
  mutate(bin = "sperm-specific")

colnames(sperm_in_sp1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")

sperm_in_sp2 <- sperm_in_sp1 %>% 
  gather("context", "methylation", 3:5)
```

```{r}
sperm_in_inter1 <- clean(sperm_in_inter) %>% 
  mutate(sample_ID = "sperm1") %>% 
  mutate(bin = "intersect.")

colnames(sperm_in_inter1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")

sperm_in_inter2 <- sperm_in_inter1 %>% 
  gather("context", "methylation", 3:5)
```


```{r}
veg1_in_egg1 <- clean(veg1_in_egg) %>% 
  mutate(sample_ID = "veg1") %>% 
  mutate(bin = "egg-specific")

colnames(veg1_in_egg1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")

veg1_in_egg2 <- veg1_in_egg1 %>% 
  gather("context", "methylation", 3:5)
```

```{r}
veg1_in_sd1 <- clean(veg1_in_sd) %>% 
  mutate(sample_ID = "veg1") %>% 
  mutate(bin = "seedling-specific")

colnames(veg1_in_sd1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")

veg1_in_sd2 <- veg1_in_sd1 %>% 
  gather("context", "methylation", 3:5)
```

```{r}
veg1_in_sp1 <- clean(veg1_in_sp) %>% 
  mutate(sample_ID = "veg1") %>% 
  mutate(bin = "sperm-specific")

colnames(veg1_in_sp1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")

veg1_in_sp2 <- veg1_in_sp1 %>% 
  gather("context", "methylation", 3:5)
```

```{r}
veg1_in_inter1 <- clean(veg1_in_inter) %>% 
  mutate(sample_ID = "veg1") %>% 
  mutate(bin = "intersect.")

colnames(veg1_in_inter1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")

veg1_in_inter2 <- veg1_in_inter1 %>% 
  gather("context", "methylation", 3:5)
```

```{r}
veg2_in_egg1 <- clean(veg2_in_egg) %>% 
  mutate(sample_ID = "veg2") %>% 
  mutate(bin = "egg-specific")

colnames(veg2_in_egg1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")

veg2_in_egg2 <- veg2_in_egg1 %>% 
  gather("context", "methylation", 3:5)
```

```{r}
veg2_in_sd1 <- clean(veg2_in_sd) %>% 
  mutate(sample_ID = "veg2") %>% 
  mutate(bin = "seedling-specific")

colnames(veg2_in_sd1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")

veg2_in_sd2 <- veg2_in_sd1 %>% 
  gather("context", "methylation", 3:5)
```

```{r}
veg2_in_sp1 <- clean(veg2_in_sp) %>% 
  mutate(sample_ID = "veg2") %>% 
  mutate(bin = "sperm-specific")

colnames(veg2_in_sp1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")

veg2_in_sp2 <- veg2_in_sp1 %>% 
  gather("context", "methylation", 3:5)
```

```{r}
veg2_in_inter1 <- clean(veg2_in_inter) %>% 
  mutate(sample_ID = "veg2") %>% 
  mutate(bin = "intersect.")

colnames(veg2_in_inter1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")

veg2_in_inter2 <- veg2_in_inter1 %>% 
  gather("context", "methylation", 3:5)
```

```{r}
veg22_in_egg1 <- clean(veg22_in_egg) %>% 
  mutate(sample_ID = "veg22") %>% 
  mutate(bin = "egg-specific")

colnames(veg22_in_egg1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")

veg22_in_egg2 <- veg22_in_egg1 %>% 
  gather("context", "methylation", 3:5)
```

```{r}
veg22_in_sd1 <- clean(veg22_in_sd) %>% 
  mutate(sample_ID = "veg22") %>% 
  mutate(bin = "seedling-specific")

colnames(veg22_in_sd1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")

veg22_in_sd2 <- veg22_in_sd1 %>% 
  gather("context", "methylation", 3:5)
```

```{r}
veg22_in_sp1 <- clean(veg22_in_sp) %>% 
  mutate(sample_ID = "veg22") %>% 
  mutate(bin = "sperm-specific")

colnames(veg22_in_sp1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")

veg22_in_sp2 <- veg22_in_sp1 %>% 
  gather("context", "methylation", 3:5)
```

```{r}
veg22_in_inter1 <- clean(veg22_in_inter) %>% 
  mutate(sample_ID = "veg22") %>% 
  mutate(bin = "intersect.")

colnames(veg22_in_inter1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")

veg22_in_inter2 <- veg22_in_inter1 %>% 
  gather("context", "methylation", 3:5)
```

```{r}
EC_in_egg1 <- clean(EC_in_egg) %>% 
  mutate(sample_ID = "EC") %>% 
  mutate(bin = "egg-specific")

colnames(EC_in_egg1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")

EC_in_egg2 <- EC_in_egg1 %>% 
  gather("context", "methylation", 3:5)
```

```{r}
EC_in_sd1 <- clean(EC_in_sd) %>% 
  mutate(sample_ID = "EC") %>% 
  mutate(bin = "seedling-specific")

colnames(EC_in_sd1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")

EC_in_sd2 <- EC_in_sd1 %>% 
  gather("context", "methylation", 3:5)
```

```{r}
EC_in_sp1 <- clean(EC_in_sp) %>% 
  mutate(sample_ID = "EC") %>% 
  mutate(bin = "sperm-specific")

colnames(EC_in_sp1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")

EC_in_sp2 <- EC_in_sp1 %>% 
  gather("context", "methylation", 3:5)
```

```{r}
EC_in_inter1 <- clean(EC_in_inter) %>% 
  mutate(sample_ID = "EC") %>% 
  mutate(bin = "intersect.")

colnames(EC_in_inter1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")

EC_in_inter2 <- EC_in_inter1 %>% 
  gather("context", "methylation", 3:5)
```

```{r}
CC_in_egg1 <- clean(CC_in_egg) %>% 
  mutate(sample_ID = "CC") %>% 
  mutate(bin = "egg-specific")

colnames(CC_in_egg1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")

CC_in_egg2 <- CC_in_egg1 %>% 
  gather("context", "methylation", 3:5)
```

```{r}
CC_in_sd1 <- clean(CC_in_sd) %>% 
  mutate(sample_ID = "CC") %>% 
  mutate(bin = "seedling-specific")

colnames(CC_in_sd1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")

CC_in_sd2 <- CC_in_sd1 %>% 
  gather("context", "methylation", 3:5)
```

```{r}
CC_in_sp1 <- clean(CC_in_sp) %>% 
  mutate(sample_ID = "CC") %>% 
  mutate(bin = "sperm-specific")

colnames(CC_in_sp1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")

CC_in_sp2 <- CC_in_sp1 %>% 
  gather("context", "methylation", 3:5)
```

```{r}
CC_in_inter1 <- clean(CC_in_inter) %>% 
  mutate(sample_ID = "CC") %>% 
  mutate(bin = "intersect.")

colnames(CC_in_inter1) <- c("chr", "start", "mCG", "mCHG", "mCHH", "sample_ID", "bin")

CC_in_inter2 <- CC_in_inter1 %>% 
  gather("context", "methylation", 3:5)
```

##plot
```{r}
g1 <- rbind(egg_in_egg2, egg_in_sd2, egg_in_sp2, egg_in_inter2,
            sperm_in_egg2, sperm_in_sd2, sperm_in_sp2, sperm_in_inter2,
            veg1_in_egg2, veg1_in_sd2, veg1_in_sp2, veg1_in_inter2,
            veg2_in_egg2, veg2_in_sd2, veg2_in_sp2, veg2_in_inter2,
            veg22_in_egg2, veg22_in_sd2, veg22_in_sp2, veg22_in_inter2,
            EC_in_egg2, EC_in_sd2, EC_in_sp2, EC_in_inter2,
            CC_in_egg2, CC_in_sd2, CC_in_sp2, CC_in_inter2) %>% 
  filter(is.na(methylation) == F) %>% 
  mutate(sample_type = case_when(
    str_detect(sample_ID, "egg") ~ "egg", 
    str_detect(sample_ID, "EC") ~ "egg",
    str_detect(sample_ID, "CC") ~ "CC",
    str_detect(sample_ID, "sperm") ~ "sperm",
    str_detect(sample_ID, "veg") ~ "pollen VC"
  )) %>% 
  mutate(bins = factor(bin, levels = c(
    "egg-specific",
    "seedling-specific",
    "sperm-specific",
    "intersect."
  ))) %>% 
  mutate(sample_type2 = case_when(
    str_detect(sample_ID, "EC") ~ "egg Park et al", 
    str_detect(sample_ID, "CC") ~ "CC Park et al",
    str_detect(sample_ID, "EC|CC") == F ~ sample_type
  )) %>% 
  mutate(sample_type = factor(sample_type2, levels = c(
    "egg", "sperm", "pollen VC", "egg Park et al", "CC Park et al"
  )))

head(g1)
```
```{r}
g1 %>% 
  ggplot(aes(x = bins, y = methylation)) +
  facet_grid(context ~ sample_type, scales = "free", switch = "both") +
  stat_summary(geom = "crossbar", fun.data = "median_hilow", aes(fill = bins), alpha = 0.8, width = 0.8) +
  scale_fill_manual(values = c("tomato1", "seagreen", "dodgerblue2", "grey60")) +
  labs(x = "methylome",
       fill = "siRNA loci",
       y = NULL) +
  theme_minimal()+
  theme(legend.position = "bottom", strip.placement = "outside") + 
  theme(text = element_text(size = 18, face="bold", colour = "black")) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_text(colour = "black"))

ggsave(filename = "rice_24nt_bin_meth_gametes_crossbar.svg", height = 5, width = 9)
```
```{r}
g1 %>% 
  filter(sample_type == "egg"|
           sample_type == "sperm") %>% 
  filter(context == "mCHH") %>% 
  ggplot(aes(x = bins, y = methylation)) +
  facet_grid(context ~ sample_type, scales = "free", switch = "both") +
  stat_summary(geom = "crossbar", fun.data = "median_hilow", aes(fill = bins), alpha = 0.8, width = 0.8) +
  scale_fill_manual(values = c("tomato1", "seagreen", "dodgerblue2", "grey60")) +
  labs(x = "methylome",
       fill = "siRNA loci",
       y = NULL) +
  theme_minimal()+
  theme(legend.position = "bottom", strip.placement = "outside") + 
  theme(text = element_text(size = 14, face="bold", colour = "black")) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_text(colour = "black")) 

ggsave(filename = "rice_24nt_bin_meth_gametes_crossbar_egg_sp.png", height = 5, width = 7.4)
```

#Stat
```{r}
test <- function(c, b){
  df1 = g1 %>% 
    filter(context == `c`) %>% 
    filter(bins == `b`)
  
  pairwise.wilcox.test(x = df1$methylation,
                       g = df1$sample_type,
                       p.adjust.method = "none")$p.value  
}
```

```{r}
bins <- c("egg-specific", "seedling-specific", "sperm-specific", "intersect.")
context <- c("mCG", "mCHG", "mCHH")
grouping <- expand.grid(bins, context) %>% as.data.frame()

colnames(grouping) <- c("bins", "context")
grouping
```
```{r}
results <- mapply(test, b = grouping$bins, c = grouping$context) %>%
  as.data.frame() 

results
```
```{r}
test(c = "mCG", b = "egg-specific")
```

```{r}
results2 <- results %>% 
  t() %>% 
  cbind(grouping) %>%
  gather("output", "p.value", 1:16) %>%  
  mutate(comparison = case_when(
    output == 1 ~ "sperm - egg",
    output == 2 ~ "pollen VC - egg",
    output == 3 ~ "egg Park et al - egg",
    output == 4 ~ "CC Park et al - egg",
    
    output == 5 ~ "sperm - sperm",
    output == 6 ~ "pollen VC - sperm",
    output == 7 ~ "egg Park et al - sperm",
    output == 8 ~ "CC Park et al - sperm",
    
    output == 9 ~ "sperm - pollen VC",
    output == 10 ~ "pollen VC - pollen VC",
    output == 11 ~ "egg Park et al - pollen VC",
    output == 12 ~ "CC Park et al - pollen VC",
    
    output == 13 ~ "sperm - egg Park et al",
    output == 14 ~ "pollen VC - egg Park et al",
    output == 15 ~ "egg Park et al - egg Park et al",
    output == 16 ~ "CC Park et al - egg Park et al"
  )) %>%
  separate(comparison, c("sample_type.x", "sample_type.y"), sep = " - ") %>%
  select(-output) %>%
  group_by(bins, context) %>%
  mutate(adjusted.p.value = p.adjust(p.value, method = "bonf")) %>%
  ungroup() %>% 
  mutate(sample_type.x = factor(sample_type.x, levels = c(
    "sperm", "pollen VC", "egg Park et al", "CC Park et al"
  ))) %>% 
 mutate(sample_type.y = factor(sample_type.y, levels = c(
    "egg", "sperm", "pollen VC", "egg Park et al"
  )))
  

results2
```
```{r}
results2 %>% 
  mutate(bins1 = case_when(
    str_detect(bins, "egg") ~ "egg-\nspecific\nloci",
    str_detect(bins, "seedling") ~ "seedling-\nspecific\nloci",
    str_detect(bins, "sperm") ~ "sperm-\nspecific\nloci",
    str_detect(bins, "intersect") ~ "intersect."
  )) %>%
  mutate(bins2 = factor(bins1, levels = c(
    "egg-\nspecific\nloci", "seedling-\nspecific\nloci", "sperm-\nspecific\nloci", "intersect."
  ))) %>%
  ggplot(aes(x = sample_type.x, y = sample_type.y)) +
  geom_tile(aes(fill = adjusted.p.value), alpha = 0.8) + 
  geom_text(aes(label = adjusted.p.value %>% round(1)), size = 5, fontface = "bold") +
  scale_fill_gradientn(colours = rev(brewer.pal(11, "Spectral")), na.value = NA) +
  labs(x = NULL,
       y = NULL, 
       fill = "adjusted\np value") + 
  facet_grid(context ~ bins2) +
  theme_minimal() +
  theme(legend.position = "bottom", legend.key.width = unit(2, units = "lines")) +
  theme(text = element_text(size = 18, face="bold")) +
  theme(axis.text.x=element_text(colour = "black", angle = 45, hjust = 1)) +
  theme(axis.text.y=element_text(colour = "black")) 

ggsave("gamete_meth_pvalues.svg", height = 6, width = 7)
```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
